sonar.host.url=https://sonarcloud.io

# Replace these placeholders with your actual keys from the SonarCloud dashboard setup
sonar.organization=anisemad
sonar.projectKey=AnisEmad_devops-hands-on-project-hivebox

# Code Analysis Configurations
sonar.sources=.
sonar.exclusions=**/test_*.py,**/*.md,k8s/**,pr_description.md
sonar.tests=.
sonar.test.inclusions=**/test_*.py

# Language Settings
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
